  version: '3.3'
  services:
    mysql:
      image: mysql:8.0
      container_name: mysql
      restart: always
      environment:
        MYSQL_DATABASE: 'elaparato'
        MYSQL_USER: 'usr-elaparato'
        MYSQL_PASSWORD: 'pwd-elaparato'
        MYSQL_ROOT_PASSWORD: 'password'
      ports:
        - '3380:3306'
      expose:
        - '3306'


